import type { DossierSection, SourceId } from './theater';
const e = (id: string, kicker: string, title: string, lead: string, points: string[], sourceIds?: SourceId[]): DossierSection => ({ id, kicker, title, lead, points, sourceIds });
export const extraContent: Record<string, { sections: DossierSection[]; next: string; nextLabel: string; quote: string }> = {
  eonet: { next: '/explore', nextLabel: 'OPEN MARS CONSOLE', quote: 'The Earth feed informs comparison questions. Mars claims still need Mars evidence.', sections: [
    e('earth-boundary', '02 / BOUNDARY', 'Earth coordinates stay on Earth', 'EONET v3 tracks Earth natural events. Only the Earth theater places those event coordinates on a map.', ['No event point is projected onto Mars.', 'The Mars console uses NASA Trek imagery.', 'The assistant prefixes Earth tool context EARTH / EONET.'], ['eonet', 'trek']),
    e('event-record', '03 / EVENT RECORD', 'Each event has its own source trail', 'The event list provides titles, categories, dates, and available point coordinates.', ['Open the EONET event record for updates.', 'An event may have no point geometry.', 'A live feed can change during a recording.'], ['eonet']),
    e('analog-question', '04 / ANALOG', 'Compare processes with care', 'Earth landscapes can inspire questions about water and sediment, while physical conditions and timescales differ from Mars.', ['Compare a process rather than transfer a hazard.', 'Name the limit of the analogy.', 'Return to Jezero sources for Mars facts.'], ['objectives']),
    e('map-key', '05 / GOOGLE MAPS', 'A browser map for Earth', 'The Google Maps JavaScript API displays EONET points when the public browser key is configured.', ['The key is restricted by site and API.', 'The event register still appears when the map is unavailable.', 'Google Maps is never the source of Mars imagery.']),
    e('return-mars', '06 / RETURN', 'Carry a question to Jezero', 'The next stop places the inquiry back on a Mars specific map and science register.', ['Switch Mars Trek layers.', 'Load the demo route.', 'Ask the local corpus for a cited answer.'], ['trekApi']),
  ] },
  targets: { next: '/hazards', nextLabel: 'VIEW WATCH ZONES', quote: 'A target marker is a prompt to inspect a source, not proof that a stop is useful or safe.', sections: [
    e('target-reading', '02 / REGISTER', 'Read the full annotation', 'Every seeded point has a category, approximate coordinate, short summary, and source link.', ['Filter by geology, mission, or other context.', 'Open the linked source.', 'Check whether the map label is an approximation.']),
    e('target-proximity', '03 / DISTANCE', 'Nearby is a geometric statement', 'The route analysis flags seed points within 2 km of the sketch, using the active route method.', ['A nearby point is not necessarily reachable.', 'The threshold does not imply scientific priority.', 'The optional PostGIS mode uses the same seed register.']),
    e('target-evidence', '04 / SOURCE', 'Separate note from observation', 'A local marker summarizes a potential context area. NASA references support the broader science, not an exact marker position.', ['Avoid citing the marker as a NASA coordinate.', 'Open the source before narration.', 'Keep image and route scales distinct.'], ['perseverance', 'hirise']),
    e('target-categories', '05 / CATEGORIES', 'More than one field question', 'Geology and mission annotations invite different questions about Jezero’s record and Perseverance’s work.', ['Name the question at each stop.', 'Compare source types before interpreting a feature.', 'Record unresolved questions in the briefing.'], ['objectives']),
    e('target-handoff', '06 / ACTION', 'Open a route from the register', 'Use Explore to see the points in their map context and to draw a hypothetical traverse.', ['Toggle the POI layer.', 'Inspect nearby point names.', 'Ask the assistant for source grounded context.']),
  ] },
  hazards: { next: '/architecture', nextLabel: 'VIEW ARCHITECTURE', quote: 'A seeded watch zone is a demonstration of uncertainty, never a clearance or hazard certification.', sections: [
    e('zone-origin', '02 / ORIGIN', 'The polygons are local seed data', 'These Jezero watch zones exist to exercise route geometry and uncertainty language.', ['They are not NASA hazard polygons.', 'Their severity labels are illustrative.', 'Do not use them to select an EVA route.']),
    e('zone-method', '03 / INTERSECTION', 'What the score checks', 'The default method samples each route segment against polygons. Optional PostGIS checks true line and polygon intersection.', ['Both methods use approximate seed shapes.', 'Neither measures slope or bearing capacity.', 'The method badge tells you which path ran.']),
    e('zone-legend', '04 / READING THE BADGE', 'A number without certification', 'The score rises when a route touches watch zones or contains more segments. It is an educational comparison measure.', ['Low does not mean safe.', 'High does not identify a real obstacle.', 'Read the risk notes with the number.']),
    e('zone-resolution', '05 / MISSING MEASUREMENTS', 'What the map cannot answer', 'A screen image cannot establish local traction, rock size, slope, or environmental operating conditions.', ['No traversability model runs here.', 'No rover hazard product is imported.', 'Use NASA source products for research context.'], ['trekApi', 'usgs']),
    e('zone-briefing', '06 / HANDOFF', 'Carry the caveat forward', 'The briefing includes terrain notes and an explicit planning only statement.', ['Review the generated PDF.', 'Keep the method visible when filming.', 'Never present the score as a safety result.']),
  ] },
  traces: { next: '/ops', nextLabel: 'SIMULATED OPERATIONS', quote: 'A process trace explains how the answer was assembled; it does not make the answer true by itself.', sections: [
    e('trace-retrieve', '02 / RETRIEVE', 'Find relevant local notes', 'The question is matched against three curated NASA source notes in the local corpus.', ['A term match yields candidate notes.', 'No match can lead to a refusal.', 'Source URLs remain attached.']),
    e('trace-earth', '03 / EARTH TOOL', 'Call only when requested', 'Earth or EONET questions may fetch event summaries from the separate NASA EONET API.', ['The tool records whether it was used.', 'Its output says EARTH / EONET.', 'It never returns Mars hazard geometry.'], ['eonet']),
    e('trace-grade', '04 / GRADE', 'Check evidence presence', 'A simple rule decides whether local notes or Earth context support a response.', ['This is a rule, not a learned confidence score.', 'Insufficient evidence produces a refusal.', 'The user can inspect citations.']),
    e('trace-assemble', '05 / TEMPLATE', 'Assemble the default answer', 'The local path formats retrieved excerpts and caveats into a cited response without a model call.', ['Cloud models require explicit opt in.', 'The video path stays local.', 'The trace labels the synthesis method.']),
    e('trace-limit', '06 / LIMIT', 'The last request lives in memory', 'The trace shown above is the latest request handled by this API process.', ['A restart clears it.', 'It is not an audit log.', 'Open the source links for factual verification.']),
  ] },
  ops: { next: '/briefing/preview', nextLabel: 'OPEN BRIEFING', quote: 'A moving display can demonstrate an interface without claiming a live mission link.', sections: [
    e('ops-sim', '02 / STATUS', 'Every tick is simulated', 'The Nest WebSocket gateway emits a sequence number, time stamp, and rotating scenario phrase every three seconds.', ['No rover is connected.', 'The time stamp is server time, not Mars mission time.', 'The banner stays visible beside the feed.']),
    e('ops-link', '03 / TRANSPORT', 'A live connection to this server', 'The browser subscribes to the /ops WebSocket namespace and updates the recent tick list.', ['Connection status changes with the socket.', 'A disconnect does not imply spacecraft status.', 'The feed is a local UI demonstration.']),
    e('ops-gauge', '04 / GLOSSARY', 'Read the display literally', '“Connected” means a socket connection to the API; “sequence” counts generated messages.', ['Neither reports rover power.', 'No atmospheric measurement is supplied.', 'No command can be sent from this page.']),
    e('ops-context', '05 / SCIENCE', 'Pair activity with evidence', 'The actual science context comes from the source linked Jezero register, not these simulated phrases.', ['Return to Explore for route metrics.', 'Open NASA mission references for observations.', 'Use the local assistant for cited context.'], ['perseverance']),
    e('ops-handoff', '06 / BRIEF', 'Move from vignette to document', 'The next screen generates a deterministic briefing from a fixed demonstration route.', ['Review metrics and source links.', 'Download the PDF.', 'Check its non-certifying statement.']),
  ] },
  pipeline: { next: '/architecture', nextLabel: 'VIEW ARCHITECTURE', quote: 'A small, explicit dataset is stronger than a claim of processing data that are not here.', sections: [
    e('pipe-tiles', '02 / RASTER', 'Trek supplies imagery', 'The browser loads NASA Trek tiles for planetary and regional viewing.', ['The app does not store a full planet raster.', 'Layer availability depends on the remote service.', 'A displayed tile is not a measured route profile.'], ['trekApi']),
    e('pipe-seed', '03 / LOCAL GEOJSON', 'Jezero is the seeded region', 'The API reads point, watch zone, and schematic footprint files from data/jezero.', ['These are demonstration annotations.', 'Their geometry is not mission certified.', 'Each source link is visible in the UI.']),
    e('pipe-corpus', '04 / CORPUS', 'Three local mission notes', 'The retrieval service reads a small Markdown corpus with titles and NASA URLs.', ['The assistant uses term based retrieval.', 'The briefing uses a fixed objective template.', 'There is no automated PDS ingest.']),
    e('pipe-earth', '05 / EARTH', 'EONET is a separate channel', 'Earth natural event summaries come through the Nest EONET module and stay Earth labeled.', ['The Earth map displays Earth geometry.', 'The Mars map displays Mars geometry.', 'A comparison does not merge the two.'], ['eonet']),
    e('pipe-output', '06 / OUTPUT', 'Deterministic deliverables', 'Route metrics and source notes form a briefing; PDFKit renders it server side.', ['Model providers are optional.', 'The score remains heuristic.', 'The output carries source and limitation text.']),
  ] },
  briefing: { next: '/targets', nextLabel: 'INSPECT TARGETS', quote: 'A briefing is useful when its measurements, sources, and limitations travel together.', sections: [
    e('brief-distance', '02 / DISTANCE', 'How length is calculated', 'The route service sums great circle segment lengths using a Mars radius approximation.', ['Each drawn waypoint defines a segment.', 'The displayed value is rounded.', 'It is not an approved EVA estimate.']),
    e('brief-risk', '03 / SCORE', 'How the terrain note is formed', 'The score uses seeded watch zone intersections and route complexity.', ['The default method is heuristic.', 'PostGIS can evaluate Jezero seed intersections.', 'Neither certifies surface safety.']),
    e('brief-points', '04 / CONTEXT', 'Why nearby points appear', 'POIs within a 2 km route corridor are listed as possible context for investigation.', ['Proximity is not a scientific conclusion.', 'Source links explain the broader feature.', 'The coordinate markers are approximate.']),
    e('brief-sources', '05 / CITATIONS', 'Where the science came from', 'The fixed objectives and local corpus connect the note to NASA mission sources.', ['Open each source to verify wording.', 'No LLM writes this briefing.', 'The PDF uses the same deterministic payload.'], ['objectives', 'perseverance']),
    e('brief-export', '06 / EXPORT', 'A portable planning record', 'The server renders a PDF containing metrics, objectives, terrain notes, nearby context, citations, and caveat.', ['A download does not validate the route.', 'Keep the caveat when sharing.', 'Return to Explore to revise the sketch.']),
  ] },
  science: { next: '/survival', nextLabel: 'RESTART THE TOUR', quote: 'The strongest claim is one that stays within the resolution and provenance of its source.', sections: [
    e('science-raster', '03 / RASTER', 'What the image resolves', 'Mars Trek displays orbital products. Pixel appearance depends on product and zoom.', ['Do not infer a micro-scale obstacle.', 'Read the layer name and source.', 'Treat color shading as visual context.'], ['trekApi']),
    e('science-geometry', '04 / GEOMETRY', 'What the annotations represent', 'Seed points and polygons are approximate communication aids around Jezero.', ['They are not NASA operational coordinates.', 'Schematic footprints are not precise image boundaries.', 'The route is hypothetical.'], ['hirise']),
    e('science-metric', '05 / METRICS', 'What the score means', 'Distance is a geometric approximation; risk is a seeded heuristic.', ['The optional spatial database changes intersection method.', 'It does not create a hazard certificate.', 'No elevation delta is reported as a measured fact.']),
    e('science-answer', '06 / ANSWER', 'How the assistant cites', 'The default pipeline retrieves local mission notes and returns their source links.', ['A citation supports the underlying note.', 'Read the original NASA context.', 'Cloud model use requires explicit opt in.'], ['perseverance', 'objectives']),
    e('science-boundary', '07 / EARTH', 'EONET never becomes Mars data', 'Earth event geometry is displayed only on Earth surfaces.', ['The labels state EARTH / EONET.', 'An Earth analogy has limits.', 'The Mars route uses Mars specific inputs.'], ['eonet']),
  ] },
  share: { next: '/explore', nextLabel: 'OPEN CONSOLE', quote: 'A share link transports a sketch, not the evidence needed to approve it.', sections: [
    e('share-payload', '02 / URL', 'What is encoded', 'The URL contains only waypoint latitude and longitude pairs.', ['No source document is embedded.', 'No safety judgment is stored.', 'The page checks point count and numeric values.']),
    e('share-restore', '03 / RESTORE', 'How Explore opens it', 'The console reads the wp query string and reconstructs a route sketch.', ['The API recalculates metrics.', 'The route remains hypothetical.', 'Source links remain separate from the URL.']),
    e('share-limits', '04 / LIMIT', 'Do not use as navigation', 'The page does not verify that the points are safe, reachable, or rover visited.', ['Coordinates are approximate.', 'Watch zones are seeded.', 'A shared link is not a certified plan.']),
    e('share-privacy', '05 / LOCAL', 'What stays on the device', 'Saved route presets use browser local storage; copied share links can be passed manually.', ['No user account is needed.', 'Clearing local storage removes saved routes.', 'The URL itself remains readable to anyone holding it.']),
    e('share-next', '06 / HANDOFF', 'Return to analysis', 'Open the route in Explore to inspect its current metrics, nearby points, and cited science.', ['Load Trek imagery.', 'Ask a local evidence question.', 'Export a new briefing.']),
  ] },
  compare: { next: '/explore', nextLabel: 'RETURN TO LOCAL EVIDENCE', quote: 'This optional experiment is outside the four-minute recording path.', sections: [
    e('compare-optin', '02 / OPT IN', 'A deliberate off-camera action', 'The comparison runs only after the user presses the comparison button.', ['The main assistant stays local by default.', 'Provider credentials stay on the API.', 'The recording path skips this page.']),
    e('compare-shared', '03 / EVIDENCE', 'One question, shared notes', 'The providers receive the same retrieved mission context for the comparison.', ['A missing key yields an unavailable message.', 'Outputs should be read against citations.', 'No model may invent route safety.']),
    e('compare-citations', '04 / SOURCES', 'Keep the register visible', 'NASA mission notes remain the reference for checking a generated response.', ['Open the cited source.', 'Check whether the answer stays within evidence.', 'Keep Earth context clearly separated.'], ['perseverance']),
    e('compare-boundary', '05 / LIMIT', 'Do not confuse synthesis with data', 'Model wording can vary; route metrics and briefing content are deterministic in the main product flow.', ['Comparison is not a mission review.', 'The model does not write the PDF.', 'The default demo needs no model key.']),
    e('compare-return', '06 / PATH', 'Go back to the console', 'The filmable path runs through local evidence, trace, simulated ops, and briefing.', ['Ask a local question.', 'Inspect the trace.', 'Export a source linked note.']),
  ] },
};
