'use client';
import LongFormExtras from './LongFormExtras';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, Printer } from 'lucide-react';
import type { Citation, MissionBriefing, RouteWaypoint } from '@mars-explorer/shared';
import { createBriefing, downloadBriefingPdf, getPlaces } from '@/lib/api';
import MissionNav from './MissionNav';
import DetailModal from './ui/DetailModal';
import Data3DSection from './scenes/Data3DSection';

export default function BriefingPreview() {
  const [waypoints, setWaypoints] = useState<RouteWaypoint[]>([]);
  const [briefing, setBriefing] = useState<MissionBriefing | null>(null);
  const [error, setError] = useState('');
  const [selectedCitation, setSelectedCitation] = useState<Citation | null>(null);
  useEffect(() => { getPlaces().then((track) => { const sols=[400,420,430]; const points=sols.map((sol,i)=>{const p=track.points.reduce((closest,point)=>Math.abs(point.sol-sol)<Math.abs(closest.sol-sol)?point:closest);return {id:`published-${i}`,lat:p.lat,lon:p.lon};}); setWaypoints(points); return createBriefing(points); }).then(setBriefing).catch((reason: Error) => setError(reason.message)); }, []);
  return <main className="theater-page briefing-theater"><MissionNav active="/briefing/preview" /><section className="briefing-sheet"><header><div><p className="eyebrow">MISSION NOTE / JEZERO · NASA PLACES PUBLISHED LOCALIZATIONS</p><h1>{briefing?.title ?? 'Traverse briefing'}</h1></div><button onClick={() => void downloadBriefingPdf(waypoints).catch((reason: Error) => setError(reason.message))}><Printer size={15} /> DOWNLOAD SERVER PDF</button></header>{error && briefing && <p className="theater-error" role="status">{error}</p>}{briefing ? <><div className="briefing-facts"><span>DISTANCE<strong>{briefing.distanceKm.toFixed(2)} KM</strong></span><span>WAYPOINTS<strong>{briefing.explorationPoints}</strong></span><span>RISK INDEX<strong>{briefing.riskIndex.total}/100 · NON-CERTIFYING</strong></span></div><section className="briefing-chapter"><h2>TRAVERSE RISK INDEX · {briefing.riskIndex.method.toUpperCase()}</h2>{briefing.riskIndex.components.map((item)=><p key={item.id}>{item.label}: +{item.score} · {item.source}</p>)}</section>{[['SCIENTIFIC OBJECTIVES', briefing.scientificObjectives], ['TERRAIN CONSIDERATIONS', briefing.terrainConsiderations], ['NEARBY CONTEXT', briefing.recommendedInvestigationPoints]].map(([title, values]) => <section className="briefing-chapter" key={title as string}><h2>{title as string}</h2>{(values as string[]).length ? (values as string[]).map((value) => <p key={value}>{value}</p>) : <p>No verified science points are attached to this route.</p>}</section>)}<section className="briefing-chapter"><h2>SOURCE REGISTER</h2>{briefing.citations.map((citation, i) => <button key={`${citation.url}-${i}`} onClick={() => setSelectedCitation(citation)}>{citation.title}<ArrowUpRight size={13} /></button>)}</section></> : <p className="theater-error">{error || 'Retrieving briefing…'}</p>}<footer>Planning aid only · DTM sampling and application risk weights are non-certifying · not for operational navigation</footer></section><Link className="brief-back-link" href="/explore">RETURN TO CONSOLE <ArrowUpRight size={14} /></Link>{waypoints.length > 1 && <Data3DSection variant="curtain" waypoints={waypoints} eyebrow="BRIEFING / ROUTE ELEVATION" title="The route, raised into a curtain." body="DEM samples along this briefing’s route, built from published PLACES positions near sols 400–430, extruded to their elevation and colored by sampled slope." cta={{ href: '/explore', label: 'OPEN IN CONSOLE' }} />}<LongFormExtras page="briefing" />{selectedCitation && <DetailModal title={selectedCitation.title} eyebrow="MISSION BRIEFING / SOURCE RECORD" summary={selectedCitation.excerpt} facts={[["MISSION", selectedCitation.mission || 'NASA'], ["ROLE", "CITED CONTEXT"]]} sources={[{ title: selectedCitation.title, url: selectedCitation.url }]} onClose={() => setSelectedCitation(null)} />}</main>;
}
