'use client';
import SceneStage from './scenes/SceneStage';
import LongFormExtras from './LongFormExtras';
import { useEffect, useState } from 'react';
import { io } from 'socket.io-client';
import MissionNav from './MissionNav';
import Link from 'next/link';

type Tick = { label: string; sequence: number; time: string; phase: string };
export default function OpsPage() {
  const [connected, setConnected] = useState(false);
  const [ticks, setTicks] = useState<Tick[]>([]);
  useEffect(() => {
    const socket = io(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000'}/ops`, { transports: ['websocket'] });
    socket.on('connect', () => setConnected(true));
    socket.on('disconnect', () => setConnected(false));
    socket.on('ops.tick', (tick: Tick) => setTicks((current) => [tick, ...current].slice(0, 12)));
    return () => { socket.disconnect(); };
  }, []);
  return <main className="theater-page"><MissionNav active="/ops" /><section className="theater-hero"><div><p className="eyebrow">MISSION CONTROL / SIMULATED</p><h1>A running operations vignette.</h1><p>These WebSocket ticks are generated by the Nest server for this demonstration. They are not rover telemetry, mission time, or a command link.</p></div><aside><span>WEBSOCKET FEED</span><strong>{connected ? 'CONNECTED' : 'WAITING'}</strong><small>SIMULATED / NOT ROVER DATA</small></aside></section><SceneStage kind="ops" className="special-scene" /><section className="theater-section"><div className="theater-section-head"><span>01 / SIMULATED EVENT STREAM</span><span>{ticks.length} RECENT TICKS</span></div><div className="theater-records">{ticks.length ? ticks.map((tick) => <article key={`${tick.time}-${tick.sequence}`}><span className="record-index">{String(tick.sequence).padStart(2,'0')}</span><div><small>{tick.label} · {new Date(tick.time).toLocaleTimeString()}</small><h2>{tick.phase}</h2><p>Demonstration state only. No spacecraft source is connected.</p></div></article>) : <p className="theater-error">{connected ? 'Waiting for the next simulated tick…' : 'Start the API to connect the simulated operations feed.'}</p>}</div></section><footer className="theater-footer"><span>SIMULATED DATA / NEVER OPERATIONAL</span><Link href="/briefing/preview">OPEN BRIEFING ↗</Link></footer><LongFormExtras page="ops" /></main>;
}
