'use client';
import { useState } from 'react';
import DetailModal from './ui/DetailModal';
import SceneStage from './scenes/SceneStage';
import LongFormExtras from './LongFormExtras';
import Link from 'next/link';
import MissionNav from './MissionNav';

const stages = [
  ['NASA MARS TREK', 'Global imagery and Jezero context load from NASA Trek tile services. Tile availability varies with network access.', 'https://trek.nasa.gov/mars/'],
  ['SEEDED JEZERO GEOJSON', 'Approximate points, watch zones, and reference footprints live in data/jezero. They are illustrative, not certified mission geometries.', '/data'],
  ['LOCAL SOURCE CORPUS', 'Three curated NASA source notes in data/corpus support retrieval and citations. This is a small demonstration corpus.', '/traces'],
  ['EARTH / EONET', 'Live Earth natural events are fetched separately from NASA EONET v3. They are never overlaid on Mars.', 'https://eonet.gsfc.nasa.gov/docs/v3'],
  ['ROUTE + BRIEFING', 'The route score is heuristic. A deterministic template produces the briefing and server PDF from metrics and cited sources.', '/briefing/preview'],
];
export default function PipelinePage() { const [selected, setSelected] = useState<number | null>(null); return <main className="theater-page"><MissionNav active="/pipeline" /><section className="theater-hero"><div><p className="eyebrow">DATA PIPELINE / HONESTY BOARD</p><h1>What this system actually holds.</h1><p>This demo combines NASA map services with a small local Jezero dataset. It does not ingest full planet PDS archives or live rover operations.</p></div><aside><span>DATA SCOPE</span><strong>JEZERO<br />DEMO</strong><small>CURATED / SOURCE LINKED</small></aside></section><SceneStage kind="layers" className="special-scene" /><section className="pipeline-status" aria-label="Data coverage board"><div><small>MARS TILES</small><strong>REMOTE / NASA TREK</strong><span>Requested on demand; availability depends on the network.</span></div><div><small>JEZERO GEOMETRY</small><strong>LOCAL / SEEDED</strong><span>Approximate GeoJSON, with optional PostGIS analysis.</span></div><div><small>EVIDENCE CORPUS</small><strong>LOCAL / CURATED</strong><span>Three source notes; no full PDS ingest.</span></div><div><small>ROVER DOWNLINK</small><strong>NOT CONNECTED</strong><span>Ops activity is explicitly simulated.</span></div></section><section className="theater-section"><div className="theater-section-head"><span>01 / DATA PATH</span><span>05 STAGES</span></div><div className="theater-records">{stages.map(([name,body,href],i) => <article key={name}><span className="record-index">{String(i+1).padStart(2,'0')}</span><div><small>PIPELINE / {name}</small><h2>{name}</h2><p>{body}</p></div><button className="record-detail-button" onClick={() => setSelected(i)} aria-label={`Inspect ${name}`}>↗</button></article>)}</div></section><footer className="theater-footer"><span>NO FULL PLANET PIPELINE / NO LIVE ROVER DATA</span><Link href="/architecture">VIEW ARCHITECTURE ↗</Link></footer><LongFormExtras page="pipeline" />{selected !== null && <DetailModal title={stages[selected][0]} eyebrow="DATA PIPELINE / PROVENANCE" summary={stages[selected][1]} facts={[["STAGE", String(selected + 1).padStart(2, '0')], ["STATUS", selected === 1 || selected === 2 ? 'LOCAL / CURATED' : 'EXTERNAL / SOURCE LINKED']]} sources={stages[selected][2].startsWith('https://') ? [{ title: stages[selected][0], url: stages[selected][2] }] : []} onClose={() => setSelected(null)}>{stages[selected][2].startsWith('/') && <Link className="detail-internal-link" href={stages[selected][2]}>OPEN RELATED APP PAGE ↗</Link>}</DetailModal>}</main>; }
